# -*- coding: utf-8 -*-


from django.db import migrations, models
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100, null=True, blank=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, null=True, blank=True)),
                ('prn', models.IntegerField(null=True, blank=True)),
                ('wat', models.CharField(max_length=255, null=True, blank=True)),
                ('watprn', models.CharField(max_length=255, null=True, blank=True)),
                ('ngr', models.CharField(max_length=11, null=True, blank=True)),
                ('ngrqual', models.CharField(max_length=50, null=True, blank=True)),
                ('map', models.CharField(max_length=13, null=True, blank=True)),
                ('unitary', models.CharField(max_length=25, null=True, blank=True)),
                ('community', models.CharField(max_length=50, null=True, blank=True)),
                ('status_typ', models.CharField(max_length=20, null=True, blank=True)),
                ('status', models.CharField(max_length=40, null=True, blank=True)),
                ('reference', models.CharField(max_length=75, null=True, blank=True)),
                ('grade', models.CharField(max_length=3, null=True, blank=True)),
                ('category', models.CharField(max_length=2, null=True, blank=True)),
                ('condition', models.CharField(max_length=50, null=True, blank=True)),
                ('broadclass', models.CharField(max_length=60, null=True, blank=True)),
                ('type', models.CharField(max_length=50, null=True, blank=True)),
                ('period', models.CharField(max_length=255, null=True, blank=True)),
                ('periodspec', models.CharField(max_length=50, null=True, blank=True)),
                ('century', models.CharField(max_length=50, null=True, blank=True)),
                ('form', models.CharField(max_length=25, null=True, blank=True)),
                ('desc_1', models.TextField(null=True, blank=True)),
                ('compiledon', models.CharField(max_length=40, null=True, blank=True)),
                ('project', models.CharField(max_length=15, null=True, blank=True)),
                ('origin', models.CharField(max_length=10, null=True, blank=True)),
                ('east', models.FloatField(null=True, blank=True)),
                ('nrth', models.FloatField(null=True, blank=True)),
                ('no_of_houses', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'verbose_name': 'Core data',
                'verbose_name_plural': 'Core data',
            },
        ),
        migrations.CreateModel(
            name='EnviroData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('old_id', models.IntegerField(null=True, blank=True)),
                ('house_number', models.IntegerField(null=True, blank=True)),
                ('site_name', models.CharField(max_length=50, null=True, blank=True)),
                ('pollen', models.CharField(max_length=50, null=True, blank=True)),
                ('pre_landscape', models.CharField(max_length=50, null=True, blank=True)),
                ('early_landscape', models.CharField(max_length=50, null=True, blank=True)),
                ('late_landscape', models.CharField(max_length=50, null=True, blank=True)),
                ('barley', models.NullBooleanField()),
                ('emmer', models.NullBooleanField()),
                ('spelt', models.NullBooleanField()),
                ('rye', models.NullBooleanField()),
                ('oats', models.NullBooleanField()),
                ('wheat_sp', models.NullBooleanField()),
                ('bread_wheat', models.NullBooleanField()),
                ('pulses', models.NullBooleanField()),
                ('flax', models.NullBooleanField()),
                ('fruit', models.NullBooleanField()),
                ('nuts', models.NullBooleanField()),
                ('other_wild', models.TextField(null=True, blank=True)),
                ('sheep_or_goat', models.NullBooleanField()),
                ('percent_sheep_or_goat', models.IntegerField(null=True, blank=True)),
                ('cow', models.NullBooleanField()),
                ('percentage_cow', models.IntegerField(null=True, blank=True)),
                ('pig', models.NullBooleanField()),
                ('percentage_pig', models.IntegerField(null=True, blank=True)),
                ('horse', models.NullBooleanField()),
                ('percentage_horse', models.IntegerField(null=True, blank=True)),
                ('other_specify', models.CharField(max_length=50, null=True, blank=True)),
                ('wild_small_mammals', models.NullBooleanField()),
                ('deer', models.NullBooleanField()),
                ('other_large_mammals', models.NullBooleanField()),
                ('birds', models.NullBooleanField()),
                ('fish', models.NullBooleanField()),
                ('shell_fish', models.NullBooleanField()),
                ('type_of_exploitation', models.CharField(max_length=50, null=True, blank=True)),
                ('soil_chemical_analysis', models.NullBooleanField()),
                ('good_chronological_res', models.CharField(max_length=50, null=True, blank=True)),
                ('notes', models.TextField(null=True, blank=True)),
                ('prn', models.ForeignKey(blank=True, to='early_celtic_society.Core', null=True)),
            ],
            options={
                'verbose_name': 'Enviro data',
                'verbose_name_plural': 'Enviro data',
            },
        ),
        migrations.CreateModel(
            name='Finds',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('finds_assemblage_id', models.IntegerField(null=True, blank=True)),
                ('site_name', models.CharField(max_length=255, null=True, blank=True)),
                ('watprn', models.CharField(max_length=255, null=True, blank=True)),
                ('quantity', models.CharField(max_length=255, null=True, blank=True)),
                ('ftype', models.CharField(max_length=255, null=True, blank=True)),
                ('fmaterial', models.CharField(max_length=255, null=True, blank=True)),
                ('datefound', models.CharField(max_length=255, null=True, blank=True)),
                ('fnotes', models.CharField(max_length=255, null=True, blank=True)),
                ('flocation', models.CharField(max_length=255, null=True, blank=True)),
                ('accno', models.CharField(max_length=255, null=True, blank=True)),
                ('bibliogref', models.CharField(max_length=255, null=True, blank=True)),
                ('animal_bone', models.NullBooleanField()),
                ('human_bone', models.NullBooleanField()),
                ('pottery', models.NullBooleanField()),
                ('fired_clay', models.NullBooleanField()),
                ('stone', models.NullBooleanField()),
                ('burnt_stone_flint', models.NullBooleanField()),
                ('plant_macro', models.NullBooleanField()),
                ('charcoal', models.NullBooleanField()),
                ('struck_worked_flint', models.NullBooleanField()),
                ('worked_stone', models.NullBooleanField()),
                ('vessels', models.NullBooleanField()),
                ('finewares', models.NullBooleanField()),
                ('briquetage', models.NullBooleanField()),
                ('cbm', models.NullBooleanField()),
                ('copper_alloy', models.NullBooleanField()),
                ('fe', models.NullBooleanField()),
                ('pb', models.NullBooleanField()),
                ('other_metal', models.NullBooleanField()),
                ('other_finds', models.NullBooleanField()),
                ('is_quantifiable_data_available', models.NullBooleanField()),
                ('coins', models.NullBooleanField()),
                ('personal_adornment', models.NullBooleanField()),
                ('decorative_fittings', models.NullBooleanField()),
                ('tools', models.NullBooleanField()),
                ('weapons', models.NullBooleanField()),
                ('metal_objects', models.NullBooleanField()),
                ('craft_production', models.NullBooleanField()),
                ('textile_production', models.NullBooleanField()),
                ('craft_working', models.NullBooleanField()),
                ('fe_metalworking', models.NullBooleanField()),
                ('non_fe_metalworking', models.NullBooleanField()),
                ('other_metalworking', models.NullBooleanField()),
                ('notes', models.TextField(null=True, blank=True)),
                ('prn', models.ForeignKey(blank=True, to='early_celtic_society.Core', null=True)),
            ],
            options={
                'verbose_name': 'Find',
                'verbose_name_plural': 'Find',
            },
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sitename', models.CharField(max_length=255, null=True, blank=True)),
                ('standard_of_data', models.IntegerField(null=True, blank=True)),
                ('earlier_activity', models.CharField(max_length=255, null=True, blank=True)),
                ('later_activity', models.CharField(max_length=255, null=True, blank=True)),
                ('phase', models.CharField(max_length=255, null=True, blank=True)),
                ('related_to', models.CharField(max_length=255, null=True, blank=True)),
                ('radiocarbon_dated', models.NullBooleanField()),
                ('dated_by_finds', models.NullBooleanField()),
                ('other_dating', models.CharField(max_length=255, null=True, blank=True)),
                ('dimensions_ha', models.CharField(max_length=255, null=True, blank=True)),
                ('altitude_m_od', models.FloatField(null=True, blank=True)),
                ('altitude_range', models.CharField(max_length=255, null=True, blank=True)),
                ('slope_class', models.CharField(max_length=50, null=True, blank=True)),
                ('site_position', models.CharField(max_length=255, null=True, blank=True)),
                ('topography', models.CharField(max_length=255, null=True, blank=True)),
                ('aspect', models.CharField(max_length=255, null=True, blank=True)),
                ('landuse_today', models.CharField(max_length=255, null=True, blank=True)),
                ('prn', models.ForeignKey(blank=True, to='early_celtic_society.Core', null=True)),
            ],
            options={
                'verbose_name': 'General Information',
                'verbose_name_plural': 'General Information',
            },
        ),
        migrations.CreateModel(
            name='HouseData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('site_name', models.CharField(max_length=50, null=True, blank=True)),
                ('house_number', models.IntegerField(null=True, blank=True)),
                ('house_location_id', models.CharField(max_length=50, null=True, blank=True)),
                ('radiocarbon_earliest', models.IntegerField(null=True, blank=True)),
                ('radiocarbon_latest', models.IntegerField(null=True, blank=True)),
                ('approx_early_date', models.CharField(max_length=50, null=True, blank=True)),
                ('approx_late_date', models.CharField(max_length=50, null=True, blank=True)),
                ('percent_excavated', models.CharField(max_length=50, null=True, blank=True)),
                ('internal_diameter', models.CharField(max_length=50, null=True, blank=True)),
                ('area', models.CharField(max_length=50, null=True, blank=True)),
                ('shape', models.CharField(max_length=50, null=True, blank=True)),
                ('repair', models.NullBooleanField()),
                ('rebuild_of', models.IntegerField(null=True, blank=True)),
                ('details', models.CharField(max_length=255, null=True, blank=True)),
                ('in_situ_decay', models.NullBooleanField()),
                ('post_removal', models.NullBooleanField()),
                ('wall_materials', models.TextField(null=True, blank=True)),
                ('stake', models.NullBooleanField()),
                ('wall_gully', models.NullBooleanField()),
                ('wall_slot', models.NullBooleanField()),
                ('plank_timber', models.NullBooleanField()),
                ('stone_wall', models.NullBooleanField()),
                ('cob_or_clay', models.NullBooleanField()),
                ('wattle', models.NullBooleanField()),
                ('rubble_or_earth_core', models.NullBooleanField()),
                ('post', models.NullBooleanField()),
                ('turf', models.NullBooleanField()),
                ('width_of_outer_wall', models.CharField(max_length=50, null=True, blank=True)),
                ('internal_post_ring', models.NullBooleanField()),
                ('other_features', models.CharField(max_length=50, null=True, blank=True)),
                ('peripery_width', models.CharField(max_length=50, null=True, blank=True)),
                ('periphery_area', models.CharField(max_length=50, null=True, blank=True)),
                ('central_zone_area', models.CharField(max_length=50, null=True, blank=True)),
                ('hearth', models.NullBooleanField()),
                ('hearth_details', models.TextField(null=True, blank=True)),
                ('internal_partitions', models.NullBooleanField()),
                ('floor_details', models.CharField(max_length=50, null=True, blank=True)),
                ('wear', models.NullBooleanField()),
                ('drain', models.NullBooleanField()),
                ('occ_deposits', models.NullBooleanField()),
                ('pits', models.NullBooleanField()),
                ('postholes', models.NullBooleanField()),
                ('stakeholes', models.NullBooleanField()),
                ('other_feat', models.NullBooleanField()),
                ('details_other', models.CharField(max_length=50, null=True, blank=True)),
                ('door_orient', models.CharField(max_length=50, null=True, blank=True)),
                ('ext_width', models.CharField(max_length=50, null=True, blank=True)),
                ('int_width', models.CharField(max_length=50, null=True, blank=True)),
                ('porch', models.NullBooleanField()),
                ('door_2_orient', models.CharField(max_length=50, null=True, blank=True)),
                ('door_2_ext', models.CharField(max_length=50, null=True, blank=True)),
                ('door_2_int', models.CharField(max_length=50, null=True, blank=True)),
                ('porch_2', models.NullBooleanField()),
                ('extra_doors', models.CharField(max_length=50, null=True, blank=True)),
                ('drainage_gully', models.NullBooleanField()),
                ('external_hearth', models.NullBooleanField()),
                ('annexe_details', models.CharField(max_length=50, null=True, blank=True)),
                ('lithics_and_production', models.CharField(max_length=50, null=True, blank=True)),
                ('querns_morts_g_stones', models.CharField(max_length=50, null=True, blank=True)),
                ('other_ground_stone', models.CharField(max_length=50, null=True, blank=True)),
                ('burnt_stone', models.CharField(max_length=50, null=True, blank=True)),
                ('vessels', models.CharField(max_length=50, null=True, blank=True)),
                ('fine_wares', models.CharField(max_length=50, null=True, blank=True)),
                ('briquetage', models.CharField(max_length=50, null=True, blank=True)),
                ('coins', models.CharField(max_length=50, null=True, blank=True)),
                ('tools', models.CharField(max_length=50, null=True, blank=True)),
                ('pers_adornment', models.CharField(max_length=50, null=True, blank=True)),
                ('dec_fittings', models.CharField(max_length=50, null=True, blank=True)),
                ('struct_fitt', models.CharField(max_length=50, null=True, blank=True)),
                ('weapon', models.CharField(max_length=50, null=True, blank=True)),
                ('textile_prod', models.CharField(max_length=50, null=True, blank=True)),
                ('other_craft_prod', models.CharField(max_length=50, null=True, blank=True)),
                ('other_metal', models.CharField(max_length=50, null=True, blank=True)),
                ('metal_working_fe', models.CharField(max_length=50, null=True, blank=True)),
                ('metal_work_non_fe', models.CharField(max_length=50, null=True, blank=True)),
                ('metal_work_unk', models.CharField(max_length=50, null=True, blank=True)),
                ('other_finds', models.CharField(max_length=50, null=True, blank=True)),
                ('cbm', models.CharField(max_length=50, null=True, blank=True)),
                ('human_bone', models.CharField(max_length=50, null=True, blank=True)),
                ('spec_dep', models.NullBooleanField()),
                ('location', models.CharField(max_length=50, null=True, blank=True)),
                ('nature', models.CharField(max_length=50, null=True, blank=True)),
                ('plant', models.NullBooleanField()),
                ('a_bone', models.NullBooleanField()),
                ('h_bone', models.NullBooleanField()),
                ('metal', models.NullBooleanField()),
                ('pottery', models.NullBooleanField()),
                ('stone', models.NullBooleanField()),
                ('other', models.NullBooleanField()),
                ('pre_house_activity', models.TextField(null=True, blank=True)),
                ('after_use', models.TextField(null=True, blank=True)),
                ('notes', models.TextField(null=True, blank=True)),
                ('links', models.CharField(max_length=50, null=True, blank=True)),
                ('mapinfo_id', models.IntegerField(null=True, blank=True)),
                ('prn', models.ForeignKey(blank=True, to='early_celtic_society.Core', null=True)),
            ],
            options={
                'verbose_name': 'House data',
                'verbose_name_plural': 'House data',
            },
        ),
        migrations.CreateModel(
            name='RadioCarbonDates',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('site_name', models.CharField(max_length=100, null=True, blank=True)),
                ('house_number', models.IntegerField(null=True, blank=True)),
                ('lab_number', models.CharField(max_length=100, null=True, blank=True)),
                ('raw_date_bp', models.IntegerField(null=True, blank=True)),
                ('error', models.IntegerField(null=True, blank=True)),
                ('calibrated_date', models.CharField(max_length=50, null=True, blank=True)),
                ('date_68_pc_low', models.IntegerField(null=True, blank=True)),
                ('date_68_pc_high', models.IntegerField(null=True, blank=True)),
                ('date_95_pc_low', models.IntegerField(null=True, blank=True)),
                ('date_95Pc_high', models.IntegerField(null=True, blank=True)),
                ('sample_location', models.CharField(max_length=100, null=True, blank=True)),
                ('sample_material', models.CharField(max_length=100, null=True, blank=True)),
                ('comment', models.CharField(max_length=255, null=True, blank=True)),
                ('prn', models.ForeignKey(blank=True, to='early_celtic_society.Core', null=True)),
            ],
            options={
                'verbose_name': 'Radio Carbon Dates',
                'verbose_name_plural': 'Radio Carbon Dates',
            },
        ),
        migrations.CreateModel(
            name='SiteAttributes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('site_name', models.CharField(max_length=100, null=True, blank=True)),
                ('simple_site_type', models.CharField(max_length=255, null=True, blank=True)),
                ('settlement_sub_type', models.CharField(max_length=255, null=True, blank=True)),
                ('rcahmw_and_smith_site_classification', models.CharField(max_length=255, null=True, blank=True)),
                ('smith_sub_type', models.FloatField(null=True, blank=True)),
                ('hillfort_dims', models.FloatField(null=True, blank=True)),
                ('hillfort_shape', models.CharField(max_length=255, null=True, blank=True)),
                ('enclosure_type', models.CharField(max_length=255, null=True, blank=True)),
                ('ext_dimensions', models.FloatField(null=True, blank=True)),
                ('int_dimensions', models.FloatField(null=True, blank=True)),
                ('associated_fields', models.NullBooleanField()),
                ('curv_fields', models.NullBooleanField()),
                ('terraced_fields', models.NullBooleanField()),
                ('enclosure_materials', models.CharField(max_length=255, null=True, blank=True)),
                ('enclosure_feature_description', models.TextField(null=True, blank=True)),
                ('no_enc_entrances', models.FloatField(null=True, blank=True)),
                ('enc_ent_orientation', models.CharField(max_length=50, null=True, blank=True)),
                ('enc_ent_type', models.CharField(max_length=255, null=True, blank=True)),
                ('enc_entrance_mat', models.CharField(max_length=255, null=True, blank=True)),
                ('ent_desc', models.TextField(null=True, blank=True)),
                ('annex_type', models.CharField(max_length=255, null=True, blank=True)),
                ('no_rhouses', models.IntegerField(null=True, blank=True)),
                ('no_longhuts', models.IntegerField(null=True, blank=True)),
                ('other', models.TextField(null=True, blank=True)),
                ('yard', models.CharField(max_length=1, null=True, blank=True)),
                ('special_dep_outside_houses', models.CharField(max_length=255, null=True, blank=True)),
                ('hillfort_project_notes', models.TextField(null=True, blank=True)),
                ('interp_comments', models.TextField(null=True, blank=True)),
                ('prn', models.ForeignKey(blank=True, to='early_celtic_society.Core', null=True)),
            ],
            options={
                'verbose_name': 'Site attributes',
                'verbose_name_plural': 'Site attributes',
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('source_id', models.IntegerField(null=True, blank=True)),
                ('wat', models.CharField(max_length=255, null=True, blank=True)),
                ('watprn', models.CharField(max_length=255, null=True, blank=True)),
                ('site_name', models.CharField(max_length=255, null=True, blank=True)),
                ('author', models.CharField(max_length=255, null=True, blank=True)),
                ('year', models.CharField(max_length=255, null=True, blank=True)),
                ('artcl_titl', models.CharField(max_length=255, null=True, blank=True)),
                ('title', models.CharField(max_length=255, null=True, blank=True)),
                ('roundhouse_project_references', models.CharField(max_length=255, null=True, blank=True)),
                ('other', models.CharField(max_length=255, null=True, blank=True)),
                ('srcetype', models.CharField(max_length=255, null=True, blank=True)),
                ('collection', models.CharField(max_length=255, null=True, blank=True)),
                ('gw_bibref', models.CharField(max_length=255, null=True, blank=True)),
                ('prn', models.ForeignKey(blank=True, to='early_celtic_society.Core', null=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('description', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('description', models.CharField(max_length=80)),
                ('sub_type', models.ForeignKey(blank=True, to='early_celtic_society.SubType', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='core',
            name='type_m2m',
            field=models.ManyToManyField(to='early_celtic_society.Type', blank=True),
        ),
    ]
